import { v4 as uuidv4 } from 'uuid';

const cardDeck = [
    {text: 'A', id: 'DEMO01'},
    {text: 'B', id: 'DEMO02'},
    {text: 'B', id: 'DEMO03'},
    {text: 'A', id: 'DEMO04'},
    {text: 'C', id: 'DEMO05'},
    {text: 'C', id: 'DEMO06'},
    {text: 'D', id: 'DEMO07'},
    {text: 'D', id: 'DEMO08'},
    {text: 'E', id: 'DEMO09'},
    {text: 'E', id: 'DEMO10'},
    {text: 'F', id: 'DEMO11'},
    {text: 'F', id: 'DEMO13'},
    {text: 'G', id: 'DEMO14'},
    {text: 'G', id: 'DEMO15'},
    {text: 'H', id: 'DEMO16'},
    {text: 'H', id: 'DEMO17'},
    {text: 'I', id: 'DEMO18'},
    {text: 'I', id: 'DEMO19'},
    {text: 'J', id: 'DEMO20'},
    {text: 'J', id: 'DEMO21'},
    {text: 'K', id: 'DEMO23'},
    {text: 'K', id: 'DEMO24'},
    {text: 'L', id: 'DEMO25'},
    {text: 'L', id: 'DEMO26'},
    {text: 'M', id: 'DEMO27'},
    {text: 'M', id: 'DEMO28'},
    {text: 'N', id: 'DEMO29'},
    {text: 'N', id: 'DEMO30'},
    {text: 'O', id: 'DEMO31'},
    {text: 'O', id: 'DEMO32'},
    {text: 'P', id: 'DEMO33'},
    {text: 'P', id: 'DEMO34'},
    {text: 'Q', id: 'DEMO35'},
    {text: 'Q', id: 'DEMO36'},
    {text: 'R', id: 'DEMO37'},
    {text: 'R', id: 'DEMO38'},
]

export default cardDeck;